development:
  secret_key_base_development: <%= ENV["SECRET_KEY_BASE_DEVELOPMENT"] %>

test:
  secret_key_base_test: <%= ENV["SECRET_KEY_BASE_TEST"] %>

production:
  secret_key_base_production: <%= ENV["SECRET_KEY_BASE"] %>
